import { Geist, Geist_Mono,Figtree } from "next/font/google";
import "./globals.css";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const figtree = Figtree({
  subsets: ["latin"],
  weight: ['400', '600', '700'],  // pick weights you want
  variable: '--font-figtree',     // optional: to use CSS variable
  display: 'swap',

});


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={figtree.variable}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} font-figtree antialiased`}
      >
        
        {children}
      </body>
    </html>
  );
}
